language: cpp

env:
  global:
    - LLVM_VERSION=5.0
    - LLVM_CONFIG="llvm-config-${LLVM_VERSION}"
    - Z3_VERSION=4.5.0
    - CVC4_VERSION=1.5
    - CLONE_DEPTH=50

cache:
  directories:
    - $TRAVIS_BUILD_DIR/downloads

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - g++
      - ninja-build
      - python-psutil
      # From sources above
      - llvm-5.0-dev
      - clang-5.0
      - clang-5.0-dev

before_script:
  # Manually install mono-devel, unfortunately we cannot use the apt mono
  # source above, because it points to an incorrect PPA.
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80
                       --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
      echo "deb http://download.mono-project.com/repo/ubuntu trusty main"
          | sudo tee /etc/apt/sources.list.d/mono-official.list;
      sudo apt-get update -qq;
      sudo apt-get install mono-devel nuget -y;
    fi

jobs:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - DEFAULT_SOLVER=z3
        - Z3="z3-${Z3_VERSION}-x64-ubuntu-14.04"
      script:
        - export BUILD_ROOT=${TRAVIS_BUILD_DIR}
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - os: linux
      dist: trusty
      sudo: required
      env:
        - DEFAULT_SOLVER=cvc4
        - CVC4="cvc4-${CVC4_VERSION}-x86_64-linux-opt"
      script:
        - export BUILD_ROOT=${TRAVIS_BUILD_DIR}
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
